config/routes.rb
Rails.application.routes.draw do
	
  
	root 'vehicles#index'

	resources :vehicles do
		resources :reviews
	end
	#resources :vehicles

	#get 'vehicles' => 'vehicles#index'
	#get 'vehicles/:id' => 'vehicles#show', as: "vehicle"
	get 'signup' => 'users#new'
	resources :users
	#resources :reviews
	resource :session	
	get "signin" => "sessions#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :vehicle

  validates :name, presence: true

  validates :comment, length: { minimum: 4 }

  STARS = [1, 2, 3, 4, 5]

  validates :stars, inclusion: {
  	in: STARS,
  	message: "must be between 1 and 5"
  }
   
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :name, presence: true

  validates :email, presence: true,
                  format: /\A\S+@\S+\z/,
                  uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 5, allow_blank: true }

	def self.authenticate(email, password)
	    user = User.find_by(email: email)
	    user && user.authenticate(password)
	end
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
	validates :make, :model, :year, :color, presence: true

	validates :features, length: { minimum: 25 }

	validates :price, :mileage, numericality: { greater_than_or_equal_to: 0}

	validates :image_file_name, allow_blank: true, format: { with: /\w+\.(gif|jpg|png)\z/i,	message: "must reference a GIF, JPG, or PNG image"
	}

	has_many :reviews, dependent: :destroy	

	def self.price_high_to_low
  	 order(price: :desc) 	
  	end
	
	def call_for_price?
    	price.blank? || price < 5000
  	end

  	def average_stars
  	  reviews.average(:stars)
  	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

private

    def require_signin
      unless current_user
      	session[:intended_url] = request.url
        redirect_to new_session_url, alert: "Please sign in first!"
      end
    end

    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    helper_method :current_user

    def current_user?(user)
      current_user == user
    end

    helper_method :current_user?

    def require_admin
      unless current_user_admin?
        redirect_to root_url, alert: "Unauthorized access!"
      end
    end

    def current_user_admin?
      current_user && current_user.admin?
    end

    helper_method :current_user_admin?
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	  before_action :set_vehicle

  def index
    @reviews = @vehicle.reviews
  end

  def new
    @review = @vehicle.reviews.new
  end

  def create
    @review = @vehicle.reviews.new(review_params)
    if @review.save
      redirect_to vehicle_reviews_path(@vehicle),
        notice: "Thanks for your review!"
    else
      render :new
    end
  end

  def show
    @review = Review.find(params[:id])
  end

  def edit
    @review = Review.find(params[:id])
  end

  def update
    @review = Review.find(params[:id])
    if @review.update(review_params)
      redirect_to vehicle_reviews_path(@vehicle), notice: "Review successfully updated!" 
    else
      render :edit
    end
  end

  def destroy
    @review = @vehicle.reviews.find(params[:id])
    @review.destroy
    redirect_to vehicle_reviews_path(@vehicle), notice: "Review successfully deleted!"
  end

private

  def review_params
    params.require(:review).permit(:name, :comment, :stars)
  end

  def set_vehicle
    @vehicle = Vehicle.find(params[:vehicle_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
    if user = User.authenticate(params[:email], params[:password])
      session[:user_id] = user.id
      flash[:notice] = "Welcome back, #{user.name}!"
      redirect_to(session[:intended_url] || user)
      session[:intended_url] = nil
    else
      flash.now[:alert] = "Invalid email/password combination!"
      render :new
    end
  end

	def destroy
	  session[:user_id] = nil
	  redirect_to root_url, notice: "You're now signed out!"
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :require_signin, except: [:new, :create]
	before_action :require_correct_user, only: [:edit, :update]
	  before_action :require_admin, only: [:destroy]


	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			redirect_to @user, notice: "Thanks for signing up!"
		else
			render :new
		end
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
		  redirect_to @user, notice: "Account successfully updated!"
		else
		  render :edit
		end
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy
		#session[:user_id] = nil
		redirect_to root_url, alert: "Account successfully deleted!"
	end

private

	def user_params
		params.require(:user).
		  permit(:name, :email, :password, :password_confirmation)
	end

	def require_correct_user
	  @user = User.find(params[:id])
	    redirect_to root_url unless current_user?(@user)
	
	end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController

	before_action :require_signin, except: [:index, :show]
	before_action :require_admin, except: [:index, :show]

  	def index
		@vehicles=Vehicle.price_high_to_low
	end

	def show
		@vehicles =Vehicle.find(params[:id])
	end

	def edit
		 @vehicles = Vehicle.find(params[:id])
	end

	def update
		@vehicles = Vehicle.find(params[:id])
		if @vehicles.update(vehicles_params)
			redirect_to @vehicles, notice: "Vehicle successfully updated!"
		else
			render :edit
		end
	end

	def new
		@vehicles = Vehicle.new
	end

	def create
		@vehicles=Vehicle.new(vehicles_params)
		if @vehicles.save
			redirect_to @vehicles, notice: "Vehicle successfully created!"
		else
			render :new
		end
	end

	def destroy
		@vehicles = Vehicle.find(params[:id])
		@vehicles.destroy
		redirect_to vehicles_url, alert: "Vehicle successfully deleted!"
	end

private
	def vehicles_params
		params.require(:vehicle).
			permit(:make, :model, :year, :price, :features, :mileage, :color, :image_file_name)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def current_user
	  User.find(session[:user_id]) if session[:user_id]
	end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
	def format_price(vehicle)
	    if vehicle.call_for_price?
	    	content_tag(:strong, 'Call for Price')
	    else
	    	number_to_currency(vehicle.price)
	   end
	end

	def format_mileage(vehicle)
		number_with_delimiter(vehicle.mileage)
	end

	def image_for(vehicle)
		if vehicle.image_file_name.blank?
			image_tag('placeholder.png')
		else
			image_tag(vehicle.image_file_name, height: '100', width: 'auto')
		end
	end

	def format_average_stars(vehicle)   
	  if vehicle.average_stars.nil?
	    content_tag(:strong, 'No reviews')
	  else
	  	  "* " * vehicle.average_stars.round
	  end
	end
	

end

app/views/layouts/_flashes.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:p, value, :class => "flash #{key}") %>
<% end %>

app/views/layouts/_footer.html.erb
<footer id="page-footer">
  <p>
  	Code Labs One Project using 
    Copyright &copy; 2018
    <%= link_to 'The Pragmatic Studio','http://pragmaticstudio.com' %>
  </p>
  <p>
    For educational purposes only.
  </p>
</footer>

app/views/layouts/_header.html.erb
<header id="page-header">
  <div id="masthead">
    <h1><%= link_to '', root_path %></h1>
    <nav>
      <p>
      	<% if current_user %>
	      	<%= link_to current_user.name, current_user %> |
	      	<%= link_to "Settings", edit_user_path(current_user) %>
	      	<%= link_to 'Sign Out', session_path, method: :delete, class: 'button' %>

	    <% else %>
	      	<%= link_to 'Sign Up', signup_path, class: 'button' %>
	        <%= link_to 'Sign In', signin_path, class: 'button' %>
	    <% end %>
      </p>
    </nav>
  </div>
</header>

app/views/layouts/_sidebar.html.erb
<aside id="sidebar">
  <nav>
    <ul>
      <li class="all-vehicles">
        <%= link_to 'All Vehicles', vehicles_path %>
      </li>
      <% if current_user_admin? %>
        <li class="create-vehicles">
          <%= link_to 'Add New Vehicle', new_vehicle_path %>
        </li>
      <% end %>
    </ul>
  </nav>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>On the Road Again</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <%= render "layouts/header" %>

    <div id="wrapper">

      <%= render "layouts/flashes" %>

      <div id="container">
        <section id="sidebar">
          <%= render "layouts/sidebar" %>
        </section>
        <section id="content">
          <%= yield %>
        </section>
      </div>

    </div>

    <%= render "layouts/footer" %>
  </body>
</html>

app/views/reviews/_form.html.erb
<%= form_for([@vehicle, @review]) do |f| %>
<%= render "shared/errors", object: @review %>
  <fieldset>
    <ol>
      <li class="required">
        <%= f.label :name %>
        <%= f.text_field :name, size: 40, autofocus: true %>
      </li>
      <li class="required stars">
        <%= f.label :stars %>
        <% Review::STARS.each do |star| %>
          <span class="star">
            <%= f.radio_button :stars, star %> <%= star %>
          </span>
        <% end %>
      </li>
      <!--<li class="required stars">
        <%= f.label :stars %>
        <%= f.select :stars, Review::STARS, prompt: "Pick one" %>
      </li>-->
      <li class="required">
        <%= f.label :comment %>
        <%= f.text_area :comment, cols: 80, placeholder: "What did you think?" %>
      </li>
    </ol>
    <p>
      <% if @review.new_record? %>
        <%= f.submit "Post Review" %>
      <% else %>
        <%= f.submit "Update Review" %>
      <% end %> |
      <%= link_to "Cancel", @vehicle, class: 'button' %>
    </p>
  </fieldset>
<% end %>

app/views/reviews/edit.html.erb
<header id="content-header">
  <h1>Edit Review for <%= link_to(@vehicle.make, @vehicle) %></h1>
</header>

<%= render 'form' %>

app/views/reviews/index.html.erb
<header id="content-header">
  <h1>Reviews for <%= link_to(@vehicle.make, @vehicle) %></h1>
  <h2><%= @vehicle.model %></h2>
</header>

<ol id="reviews">
  <% @reviews.each do |review| %>
    <li>
      <span class="review"><%= pluralize(review.stars, 'star') %></span>
      <span class="user">by <%= link_to (review.name), vehicle_review_path(@vehicle, review.id) %></span>
      <span class="date"><%= time_ago_in_words(review.created_at) %> ago</span>
      <p>
        &quot;<%= review.comment %>&quot;
      </p>
    </li>
  <% end %>
</ol>

app/views/reviews/new.html.erb
<header id="content-header">
  <h1>New Review for <%= link_to(@vehicle.make, @vehicle) %></h1>
</header>

<%= render 'form' %>

app/views/reviews/show.html.erb
<header id="content-header">
	<h2><%= @review.name %>'s Review of <%= link_to @vehicle.make, @vehicle %></h2><h3><%= @vehicle.model %></h3>
</header>

<%= link_to pluralize(@vehicle.make, 'Review'),vehicle_reviews_path(@vehicle), class: 'button' %>


<article id="vehicle" class="vehicle">
  <h3><%= @review.stars %> Stars</h3>
    
  <h3>Comments</h3>
  <p>
    <%= @review.comment %>
  </p>
</article>

<footer>
	<nav>
		<p>
			<%= link_to 'Edit', edit_vehicle_review_path(@vehicle, @review), class: 'button' %>
			  <%= link_to 'Delete', [@vehicle, @review], 
			                  class: 'button',
			                  method: :delete, data: { confirm: 'Are you sure?' } %>
		</p>
	</nav>
</footer>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
<section id="errors">
  <header>
    <h2>
      Oops! The <%= object.class.name.humanize.downcase  %> could not be saved. 
    </h2>
    <h3>
      Please correct the following <%= pluralize(object.errors.count, "error") %>:
    </h3>
  </header>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</section>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render "shared/errors", object: @user %>
  <fieldset>
    <ol>
      <li class="required">
        <%= f.label :name %>
        <%= f.text_field :name, size: 40, autofocus: true %>
      </li>
      <li class="required">
        <%= f.label :email %>
        <%= f.email_field :email, size: 40 %>
      </li>
      <li class="required">
        <%= f.label :password %>
        <%= f.password_field :password, size: 40 %>
      </li>
      <li class="required">
        <%= f.label :password_confirmation, "Confirm Password" %>
        <%= f.password_field :password_confirmation, size: 40 %>
      </li>
    </ol>
    <p>
      <% if @user.new_record? %>
        <%= f.submit "Create Account" %>
      <% else %>
        <%= f.submit "Update Account" %>
      <% end %>
    </p>
  </fieldset>
<% end %>

app/views/users/edit.html.erb
<header id="content-header">
  <h1>Edit Account</h1>
</header>

<%= render 'form' %>

app/views/users/index.html.erb
<header id="content-header">
  <h1><%= pluralize(@users.size, 'User') %></h1>
</header>

<ul id="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %>
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<header id="content-header">
  <h1>Sign Up</h1>
</header>

<%= render 'form' %>

app/views/users/show.html.erb
<article id="user">
  <header>
    <h1><%= @user.name %></h1>
    <h2><%= mail_to(@user.email) %></h2>
    <h3>Member Since</h3>
      <p>
        <%= @user.created_at.strftime("%B %Y") %>
      </p>
  </header>

  <footer>
    <nav>
      <% if current_user?(@user) %>
        <%= link_to 'Edit Account', edit_user_path(@user), class: 'button' %>
      <% end %>
      <% if current_user_admin? %>
        <%= link_to 'Delete Account', @user,
                    method: :delete,
                    data: { confirm: 'Are you sure you want to permanently delete your account?' },
                    class: 'button' %>
      <% end %>
    </nav>
  </footer>
</article>

app/views/vehicles/_form.html.erb
<%= form_for(@vehicles) do |f| %>
  <%= render "shared/errors", object: @vehicles %>
  <fieldset>
    <ol>
      <li class="required">
        <%= f.label :make %><br/>
        <%= f.text_field :make, autofocus: true %>
      </li>
      <li class="required">
        <%= f.label :model %><br/>
        <%= f.text_field :model %>
      </li>
      <li class="required">
        <%= f.label :year %><br/>
        <%= f.select :year, Date.today.year-50 .. Date.today.year+5 %>
      </li>
      <li class="required">
        <%= f.label :price %><br/>
        <%= f.number_field :price %>
      </li>
      <li class="required">
        <%= f.label :features %><br/>
        <%= f.text_area :features, cols: 40, rows: 3 %>
      </li>
      <li class="required">
        <%= f.label :mileage %><br/>
        <%= f.number_field :mileage %>
      </li>
      <li class="required">
        <%= f.label :color %><br/>
        <%= f.text_field :color %>
      </li>
      <li>
        <%= f.label :image_file_name %><br/>
        <%= f.text_field :image_file_name, size: 30, 
              lilaceholder:"GIF, JliG, or liNG file name" %>
      </li>
    </ol> 
    <p>
      <%= f.submit %> |
      <%= link_to "Cancel", vehicles_path, class: 'button' %>
    </p>
  </fieldset>
<% end %>

app/views/vehicles/edit.html.erb
<header id="content-header">
	<h1>Editing </h1>
	<h2><%= @vehicles.make %></h2>
	<h3><%= @vehicles.model %></h3>
</header>

<%= render 'form' %>

app/views/vehicles/index.html.erb
<ul id="vehicles">
  <% @vehicles.each do |vehicle| %>
  <li>
    <article class="vehicle">
      <header>
        <h2><%= link_to(vehicle.make, vehicle) %></h2>
          <%= link_to vehicle_path(vehicle.id) do %> 
            <%= image_for(vehicle) %>
          <% end %>
      </header>
      <p>
        <%= truncate(vehicle.features, length: 40, separator: ' ') %>
      </p>
      <table>
        <tr>
          <th>Model:</th>
          <td><%= vehicle.model %></td>
        </tr>
        <tr>
          <th>Year:</th>
          <td><%= vehicle.year %></td>
        </tr>
        <tr>
          <th>Price:</th>
          <td><%= format_price(vehicle) %></td>
        </tr>
        <tr>
          <th>Miles:</th>
          <td><%= format_mileage(vehicle) %></td>
        </tr>
        <tr>
          <th>Color:</th>
          <td><%= vehicle.color %></td>
        </tr>
      </table>
      <footer>
      </footer>
    </article>
  </li>
<% end %>
</ul>

app/views/vehicles/new.html.erb
<header id="content-header">
  <h1>Add New Vehicle</h1>
</header>

<%= render 'form' %>

app/views/vehicles/show.html.erb
<article id="vehicle" class="vehicle">
    <header>
      <h2><%= @vehicles.make %> <%= @vehicles.model %></h2>
      <%= image_for(@vehicles) %>
    </header>
    <p>
      <%= @vehicles.features %>
    </p>
    <table>
      <tr>
        <th>Year:</th>
        <td><%= @vehicles.year %></td>
      </tr>
      <tr>
        <th>Price:</th>
        <td><%= format_price(@vehicles) %></td>
      </tr>
      <tr>
        <th>Miles:</th>
        <td><%= format_mileage(@vehicles) %></td>
      </tr>
      <tr>
        <th>Color:</th>
        <td><%= @vehicles.color %></td>
      </tr>
    </table>

    <h3>Reviews</h3>
      <%= link_to pluralize(@vehicles.reviews.size, 'Review'), vehicle_reviews_path(@vehicles) %>
      &nbsp;
      <%= format_average_stars(@vehicles) %>    

  </article>
  <br>

  <footer>
    <p>
      <%= link_to "Write Review", new_vehicle_review_path(@vehicles),
               class: 'button ok review' %>
    </p>
    <nav>
      <% if current_user_admin? %>
        <%= link_to 'Edit', edit_vehicle_path(@vehicles), class: 'button' %>
        <%= link_to 'Delete', @vehicles, 
                    class: 'button',
                    method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
    </nav>
  </footer>
  